...
        timestamp_info = consumer.committed([tp])
        if timestamp_info and len(timestamp_info) > 0:
            timestamp = timestamp_info[0].offset
            last_activity = datetime.utcfromtimestamp(timestamp / 1000.0) if timestamp else None
...
